// Values generated by Jagannatha Hora itself (Lahiri, true nodes) for 1996-12-07 10:34:00 IST, Chennai 13.03862 N 80.261818 E,
// as recorded in PyJHora's test-suite (chart_element_longitude_tests). The one oracle that is the real program.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { getEph } from './helpers.mjs';
import { computeChart } from '../src/chart.js';
import { computeUpagrahas } from '../src/upagrahas.js';
import { computeSpecialLagnas } from '../src/lagnas.js';
import { norm360 } from '../src/time.js';

const INPUT = { year: 1996, month: 12, day: 7, hour: 10, minute: 34, second: 0, utcOffset: 5.5, lat: 13.03862, lon: 80.261818 };
const SIGNS = ['Ar', 'Ta', 'Ge', 'Cn', 'Le', 'Vi', 'Li', 'Sc', 'Sg', 'Cp', 'Aq', 'Pi'];
const parse = (s) => { const m = s.match(/^(\d+) (\w\w) (\d+)' ([\d.]+)"$/); return SIGNS.indexOf(m[2]) * 30 + +m[1] + +m[3] / 60 + +m[4] / 3600; };
const JH = {
  lagna: "22 Cp 26' 38.05\"", planets: ["21 Sc 33' 55.15\"", "6 Li 57' 34.30\"", "25 Le 32' 23.23\"", "9 Sg 56' 11.35\"", "25 Sg 49' 41.12\"", "23 Li 43' 01.82\"", "6 Pi 48' 26.33\"", "11 Vi 42' 07.68\"", "11 Pi 42' 07.68\""],
  upagrahas: { Kala: "11 Cp 41' 54.73\"", Mrityu: "29 Aq 51' 43.90\"", Ardhaprahara: "25 Pi 22' 08.35\"", Yamaghantaka: "19 Ar 32' 23.44\"", Gulika: "21 Sc 23' 25.93\"", Mandi: "0 Sg 58' 57.47\"", Dhuma: "4 Ar 53' 55.15\"", Vyatipata: "25 Pi 06' 04.85\"", Parivesha: "25 Vi 06' 04.85\"", Indrachapa: "4 Li 53' 55.15\"", Upaketu: "21 Li 33' 55.15\"" },
  lagnas: { 'Bhava lagna': "24 Cp 25' 46.37\"", 'Hora lagna': "27 Pi 17' 37.59\"", 'Ghati lagna': "5 Li 53' 11.23\"", 'Pranapada lagna': "18 Cp 50' 59.46\"", 'Vighati lagna': "18 Ta 50' 59.46\"", 'Kunda lagna': "17 Cp 57' 22.43\"", 'Bhrigu Bindu': "24 Vi 19' 50.99\"", 'Sree lagna': "0 Aq 21' 04.18\"", 'Indu lagna': "6 Cp 57' 34.30\"", 'Varnada lagna': "22 Sg 26' 38.05\"" },
};
const diffSec = (a, b) => Math.abs(norm360(a - b + 180) - 180) * 3600;

test('Jagannatha Hora reference: Lagna and nine grahas within 2 arcseconds', async () => {
  const eph = await getEph();
  const c = computeChart(eph, INPUT);
  assert.ok(diffSec(c.asc, parse(JH.lagna)) < 2, `lagna ${diffSec(c.asc, parse(JH.lagna))}"`);
  JH.planets.forEach((s, p) => assert.ok(diffSec(c.planets[p].lon, parse(s)) < 2, `planet ${p}: ${diffSec(c.planets[p].lon, parse(s)).toFixed(2)}"`));
});

test('Jagannatha Hora reference: solar upagrahas within 1", kalavelas within 40" (its sunrise is ~2 s later)', async () => {
  const eph = await getEph();
  const c = computeChart(eph, INPUT);
  const U = Object.fromEntries(computeUpagrahas(eph, c).map(u => [u.name, u.lon]));
  for (const [name, s] of Object.entries(JH.upagrahas)) {
    const tol = ['Dhuma', 'Vyatipata', 'Parivesha', 'Indrachapa', 'Upaketu'].includes(name) ? 1 : 40;
    assert.ok(diffSec(U[name], parse(s)) < tol, `${name}: ${diffSec(U[name], parse(s)).toFixed(1)}" (tolerance ${tol}")`);
  }
});

test('Jagannatha Hora reference: special lagnas (time-based within the 2 s sunrise difference; positional within 2″)', async () => {
  const eph = await getEph();
  const c = computeChart(eph, INPUT);
  const L = Object.fromEntries(computeSpecialLagnas(eph, c).map(u => [u.name, u.lon]));
  // Jagannatha Hora's sunrise for this chart is ≈2.2 s later than Swiss Ephemeris' true rise of the disc centre; tolerances scale with each lagna's rate
  const tol = { 'Bhava lagna': 45, 'Hora lagna': 90, 'Ghati lagna': 200, 'Pranapada lagna': 720, 'Vighati lagna': 720, 'Kunda lagna': 170, 'Bhrigu Bindu': 2, 'Sree lagna': 30, 'Indu lagna': 2, 'Varnada lagna': 2 }; // Sree lagna multiplies the Moon's position error by 27
  for (const [name, s] of Object.entries(JH.lagnas)) assert.ok(diffSec(L[name], parse(s)) < tol[name], `${name}: ${diffSec(L[name], parse(s)).toFixed(1)}" (tolerance ${tol[name]}")`);
});
